FROM luckydonald/telegram-bot:%%PLACEHOLDER%%

LABEL docker.image.base="luckydonald/telegram-bot:%%PLACEHOLDER%%-onbuild"
LABEL docker.image.base.author="luckydonald"
LABEL docker.image.base.url.github="https://github.com/luckydonald/docker-telegram-bot"
LABEL docker.image.base.url.docker="https://hub.docker.com/r/luckydonald/telegram-bot/"

ONBUILD COPY $FOLDER/requirements.txt   /config/
ONBUILD RUN pip install --no-cache-dir -r /config/requirements.txt

ONBUILD COPY $FOLDER/code /app
