FROM luckydonald/telegram-bot:%%PLACEHOLDER%%

LABEL docker.image.base="luckydonald/telegram-bot:%%PLACEHOLDER%%-onbuild"

# automatically install requirements.txt and copy the code folder
ONBUILD COPY $FOLDER/requirements.txt   /config/
ONBUILD RUN pip install --no-cache-dir -r /config/requirements.txt

ONBUILD COPY $FOLDER/code /app
